package interface_adapter.changebackgroundcolor;

import use_case.changebackgroundcolor.ChangeBackgroundColorOutputBoundary;

public class ChangeBackgroundColorPresenter implements ChangeBackgroundColorOutputBoundary {
}
